# Site
name: "Concept cars"
title: "Concept cars"
description: "Website about concept cars and their mass production cars"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl:
google_analytics:
disqus: 'demowebsite'
mailchimp-list:
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  domas:
    name: Domas
    display_name: Domas
    avatar:
    gravatar: fbf5601bd9a73bc4bead0e79b3e11419
    email: domas.lescinskas@gmail.com
    web: https://github.com/domasles
    description: Domas L.

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
